INSERT INTO posts (orig_id, url, title) VALUES(2,'https://blog.starkandwayne.com/2013/02/14/diy-paas-staging-an-app','DIY PaaS - staging an app');
INSERT INTO posts (orig_id, url, title) VALUES(3,'https://blog.starkandwayne.com/2013/04/12/jenkins-builds-from-cli','Jenkins builds from CLI');
INSERT INTO posts (orig_id, url, title) VALUES(4,'https://blog.starkandwayne.com/2013/01/28/company-create','Company.create');
INSERT INTO posts (orig_id, url, title) VALUES(5,'https://blog.starkandwayne.com/2014/07/31/upgrading-trycf-for-power-users','Upgrading TryCF for Power Users');
INSERT INTO posts (orig_id, url, title) VALUES(6,'https://blog.starkandwayne.com/2013/02/05/diy-paas-running-apps-with-a-dea','DIY PaaS - running apps with a DEA');
INSERT INTO posts (orig_id, url, title) VALUES(8,'https://blog.starkandwayne.com/2013/04/09/run-sidekiq-on-cloud-foundry','Run Sidekiq on Cloud Foundry');
INSERT INTO posts (orig_id, url, title) VALUES(9,'https://blog.starkandwayne.com/2013/03/27/did-you-know-you-can-use-puma-in-cloud-foundry','Did you know you can use Puma in Cloud Foundry?');
INSERT INTO posts (orig_id, url, title) VALUES(10,'https://blog.starkandwayne.com/2013/03/20/boot-up-cloud-foundry','Boot up Cloud Foundry');
INSERT INTO posts (orig_id, url, title) VALUES(11,'https://blog.starkandwayne.com/2013/02/22/thoughts-on-cloud-foundrys-oss-community','Thoughts on Cloud Foundry''s OSS Community');
INSERT INTO posts (orig_id, url, title) VALUES(12,'https://blog.starkandwayne.com/2014/05/16/self-healing-services-ugrading-their-own-dns','Services upgrading their own DNS');
INSERT INTO posts (orig_id, url, title) VALUES(13,'https://blog.starkandwayne.com/2013/04/22/ruby-console-for-jenkins','Ruby console for Jenkins');
INSERT INTO posts (orig_id, url, title) VALUES(14,'https://blog.starkandwayne.com/2013/04/24/welcome-and-thanks-pivotal','Welcome and thanks Pivotal');
INSERT INTO posts (orig_id, url, title) VALUES(7,'https://blog.starkandwayne.com/2014/08/06/markdown-for-quasi-beginners','Markdown for quasi-Beginners');
INSERT INTO posts (orig_id, url, title) VALUES(15,'https://blog.starkandwayne.com/2014/05/13/worlds-quickest-demo-of-consul','World''s quickest demo of consul');
INSERT INTO posts (orig_id, url, title) VALUES(16,'https://blog.starkandwayne.com/2013/05/07/tdd-your-devops-with-test-kitchen','TDD your DevOps with test-kitchen 1.0');
INSERT INTO posts (orig_id, url, title) VALUES(17,'https://blog.starkandwayne.com/2013/07/08/simple-redis-service-built-on-bosh','Simple redis service built on BOSH');
INSERT INTO posts (orig_id, url, title) VALUES(18,'https://blog.starkandwayne.com/2014/01/27/bosh-packages-with-debian','BOSH packages with Debian');
INSERT INTO posts (orig_id, url, title) VALUES(19,'https://blog.starkandwayne.com/2014/02/10/playing-with-private-docker','Playing with Private Docker');
INSERT INTO posts (orig_id, url, title) VALUES(20,'https://blog.starkandwayne.com/2013/12/02/rapidly-develop-bosh-releases-with-bosh-gen-and-bosh-lite','Rapidly develop BOSH releases with bosh-gen and bosh-lite');
INSERT INTO posts (orig_id, url, title) VALUES(21,'https://blog.starkandwayne.com/2014/05/10/using-a-postgres-uri-with-psql','Using a postgres URI with psql');
INSERT INTO posts (orig_id, url, title) VALUES(23,'https://blog.starkandwayne.com/2014/05/08/deploy-ghost-blog-to-cloud-foundry','Deploy Ghost blog to Cloud Foundry');
INSERT INTO posts (orig_id, url, title) VALUES(103,'https://blog.starkandwayne.com/2015/04/17/pgconf-nyc-2015','PGConf NYC 2015');
INSERT INTO posts (orig_id, url, title) VALUES(104,'https://blog.starkandwayne.com/2015/04/24/creating-and-maintaining-a-positive-user-experience-with-cloud-foundry-and-bosh','Creating and Maintaining a Positive User Experience with Cloud Foundry and BOSH');
INSERT INTO posts (orig_id, url, title) VALUES(25,'https://blog.starkandwayne.com/2014/05/14/dynamic-dns-based-on-consul-health-checks','Dynamic DNS based on consul health checks');
INSERT INTO posts (orig_id, url, title) VALUES(26,'https://blog.starkandwayne.com/2014/05/22/demo-of-a-manual-failover-of-redis-cluster-atop-of-consulconfd','Demo of a manual failover of redis cluster atop of consul/confd');
INSERT INTO posts (orig_id, url, title) VALUES(27,'https://blog.starkandwayne.com/2014/05/24/building-agents-in-go-that-work-with-consul-agent','Building agents in Go that talk with Consul agent');
INSERT INTO posts (orig_id, url, title) VALUES(28,'https://blog.starkandwayne.com/2014/05/29/guaranteeing-the-future-for-developers-with-the-cloud-foundry-foundation','Guaranteeing the future for developers with the Cloud Foundry Foundation');
INSERT INTO posts (orig_id, url, title) VALUES(29,'https://blog.starkandwayne.com/2014/05/30/small-to-mid-range-cloud-foundry-closing-the-gap','Small to Mid-Range Cloud Foundry - Closing The Gap');
INSERT INTO posts (orig_id, url, title) VALUES(30,'https://blog.starkandwayne.com/2014/05/30/running-bosh-lite-on-vsphere-hypervisor-free-edition','Running bosh-lite on vSphere Hypervisor Free Edition');
INSERT INTO posts (orig_id, url, title) VALUES(31,'https://blog.starkandwayne.com/2014/06/30/one-stop-shop-for-bosh-releases','One-stop shop for BOSH releases');
INSERT INTO posts (orig_id, url, title) VALUES(32,'https://blog.starkandwayne.com/2014/06/30/making-bosh-releases-more-social','Making BOSH releases more social');
INSERT INTO posts (orig_id, url, title) VALUES(33,'https://blog.starkandwayne.com/2014/06/23/how-to-install-splunk-and-the-boundary-plugin-on-a-new-centos-6-5-install','How to install Splunk and the Boundary plugin on a new CentOS 6.5 install');
INSERT INTO posts (orig_id, url, title) VALUES(34,'https://blog.starkandwayne.com/2014/06/19/converting-openstack-qcow2-stemcell-to-raw-stemcell','Converting Openstack QCOW2 stemcell to RAW stemcell');
INSERT INTO posts (orig_id, url, title) VALUES(35,'https://blog.starkandwayne.com/2014/06/27/quick-guide-to-using-monit-in-bosh','Quick guide to using Monit in BOSH');
INSERT INTO posts (orig_id, url, title) VALUES(36,'https://blog.starkandwayne.com/2014/07/02/adding-mysql-service-to-your-trycf-cloud-foundry','Adding MySQL service to your TryCF Cloud Foundry');
INSERT INTO posts (orig_id, url, title) VALUES(37,'https://blog.starkandwayne.com/2014/08/11/host-static-sites-on-cloud-foundry','Host static sites on Cloud Foundry');
INSERT INTO posts (orig_id, url, title) VALUES(41,'https://blog.starkandwayne.com/2014/07/10/automatic-resurrection-with-binary-bosh','Automatic resurrection with Binary BOSH');
INSERT INTO posts (orig_id, url, title) VALUES(42,'https://blog.starkandwayne.com/2014/07/07/bosh-lite-on-bare-metal','Bosh-lite on bare-metal');
INSERT INTO posts (orig_id, url, title) VALUES(57,'https://blog.starkandwayne.com/2014/09/19/new-languages-new-woes-tonights-golang-roadblock','New languages, new woes: tonight’s Golang roadblock');
INSERT INTO posts (orig_id, url, title) VALUES(44,'https://blog.starkandwayne.com/2014/07/10/resurrecting-bosh-with-binary-boshes','Highly available BOSH with Binary BOSHes');
INSERT INTO posts (orig_id, url, title) VALUES(47,'https://blog.starkandwayne.com/2014/07/29/using-mdpress-and-deck2pdf-for-presentations','Using mdpress and deck2pdf for Presentations');
INSERT INTO posts (orig_id, url, title) VALUES(49,'https://blog.starkandwayne.com/2014/07/14/running-one-time-tasks-in-cloud-foundry','Running one-time tasks in Cloud Foundry');
INSERT INTO posts (orig_id, url, title) VALUES(50,'https://blog.starkandwayne.com/2014/08/02/your-first-bosh-release','Your first BOSH Release');
INSERT INTO posts (orig_id, url, title) VALUES(55,'https://blog.starkandwayne.com/2014/09/08/adding-extensions-to-php-buildpack','Adding extensions to PHP buildpack');
INSERT INTO posts (orig_id, url, title) VALUES(46,'https://blog.starkandwayne.com/2014/10/02/using-bosh-workspace-to-deploy-cloud-foundry-on-aws','Easy Cloud Foundry upgrading with bosh-workspace');
INSERT INTO posts (orig_id, url, title) VALUES(82,'https://blog.starkandwayne.com/2015/04/19/bosh-init-can-deploy-anything-anywhere-anytime','New bosh-init can deploy anything to a single server');
INSERT INTO posts (orig_id, url, title) VALUES(39,'https://blog.starkandwayne.com/2014/08/11/baas-a-quick-metaphor-about-aas','BaaS: A quick metaphor about *aaS');
INSERT INTO posts (orig_id, url, title) VALUES(24,'https://blog.starkandwayne.com/2014/05/21/bootstrapping-a-bootstrap-less-consul-cluster-with-bosh','Bootstrapping a bootstrap-less consul cluster with BOSH');
INSERT INTO posts (orig_id, url, title) VALUES(83,'https://blog.starkandwayne.com/2015/02/25/increasing-bosh-lite-vm-memory-size','Increasing BOSH-lite vm memory size');
INSERT INTO posts (orig_id, url, title) VALUES(52,'https://blog.starkandwayne.com/2014/08/02/ask-pat-how-long-does-it-take-to-push-apps','Ask PAT: how long does it take to push apps?');
INSERT INTO posts (orig_id, url, title) VALUES(54,'https://blog.starkandwayne.com/2014/09/04/jeff-lindsays-automatic-service-registration-of-docker-containers','Jeff Lindsay''s automatic service registration of Docker containers');
INSERT INTO posts (orig_id, url, title) VALUES(56,'https://blog.starkandwayne.com/2014/09/13/deploying-cfplayground-to-cloud-foundry','Deploying Cloud Foundry Playground to Cloud Foundry');
INSERT INTO posts (orig_id, url, title) VALUES(58,'https://blog.starkandwayne.com/2014/10/03/bootstrap-microbosh-to-aws-vpc','Bootstrap MicroBOSH to AWS VPC');
INSERT INTO posts (orig_id, url, title) VALUES(40,'https://blog.starkandwayne.com/2014/10/10/restore-micro-bosh-from-just-its-persistent-disk','Restore Micro BOSH from just its persistent disk');
INSERT INTO posts (orig_id, url, title) VALUES(86,'https://blog.starkandwayne.com/2015/03/18/installing-bosh-cli-on-centos-7-stub','Installing BOSH CLI on CentOS 7');
INSERT INTO posts (orig_id, url, title) VALUES(84,'https://blog.starkandwayne.com/2015/03/04/installing-cloud-foundry-cli-plugins','Installing Cloud Foundry CLI plugins');
INSERT INTO posts (orig_id, url, title) VALUES(85,'https://blog.starkandwayne.com/2015/03/12/multi-tenant-elk-for-your-private-cloud-foundry','Multi-tenant ELK for your private Cloud Foundry');
INSERT INTO posts (orig_id, url, title) VALUES(60,'https://blog.starkandwayne.com/2014/10/28/ssh-into-cloud-foundry-containers-from-windows','SSH into Cloud Foundry containers from Windows');
INSERT INTO posts (orig_id, url, title) VALUES(59,'https://blog.starkandwayne.com/2014/10/16/terraforming-workloads-with-docker-and-digital-ocean','Terraforming workloads with Docker and Digital Ocean');
INSERT INTO posts (orig_id, url, title) VALUES(90,'https://blog.starkandwayne.com/2015/03/24/speed-up-the-staticfile-buildpack-only-deploy-the-dist-folder','Speed up the Staticfile buildpack: only deploy the dist folder');
INSERT INTO posts (orig_id, url, title) VALUES(63,'https://blog.starkandwayne.com/2014/11/04/running-galaxy-on-cloud-foundry','Running Galaxy on Cloud Foundry');
INSERT INTO posts (orig_id, url, title) VALUES(62,'https://blog.starkandwayne.com/2014/10/30/fixing-loggregator-problems-one-problem-at-a-time','Fixing Loggregator problems one problem at a time.');
INSERT INTO posts (orig_id, url, title) VALUES(87,'https://blog.starkandwayne.com/2015/03/19/managing-multiple-boshs','Multiple BOSHs and users on the same machine.');
INSERT INTO posts (orig_id, url, title) VALUES(97,'https://blog.starkandwayne.com/2015/04/01/keeping-an-eye-on-cloud-foundry-pt-1','Keeping an eye on Cloud Foundry Pt. 1');
INSERT INTO posts (orig_id, url, title) VALUES(61,'https://blog.starkandwayne.com/2014/10/28/how-does-cf-ssh-get-you-an-ssh-session-into-cloud-foundry','How does cf-ssh get you an SSH session into Cloud Foundry?');
INSERT INTO posts (orig_id, url, title) VALUES(108,'https://blog.starkandwayne.com/2015/05/04/wait-until-ssh-is-available','Wait until SSH is available');
INSERT INTO posts (orig_id, url, title) VALUES(105,'https://blog.starkandwayne.com/2015/04/28/embed-docker-into-bosh-releases','Embed absolutely anything into BOSH releases using Docker');
INSERT INTO posts (orig_id, url, title) VALUES(64,'https://blog.starkandwayne.com/2014/10/31/public-and-private-microservices-on-the-same-cloud-foundry','Public and private microservices on the same Cloud Foundry');
INSERT INTO posts (orig_id, url, title) VALUES(106,'https://blog.starkandwayne.com/2015/05/01/flattening-the-dockerbosh-workflow','Flattening the Docker/BOSH workflow');
INSERT INTO posts (orig_id, url, title) VALUES(66,'https://blog.starkandwayne.com/2014/11/11/simple-golang-oauth-client-for-cf','Simple Golang OAuth client for Cloud Foundry');
INSERT INTO posts (orig_id, url, title) VALUES(45,'https://blog.starkandwayne.com/2014/07/11/hey-windows-users-you-too-can-haz-ssh','Hey Windows Users - You Too Can Haz SSH!');
INSERT INTO posts (orig_id, url, title) VALUES(67,'https://blog.starkandwayne.com/2014/11/12/deploying-wordpress-to-cloud-foundry','Deploying Wordpress to Cloud Foundry');
INSERT INTO posts (orig_id, url, title) VALUES(68,'https://blog.starkandwayne.com/2014/11/12/bosh-lite-can-be-better-on-aws','bosh-lite can be better on AWS');
INSERT INTO posts (orig_id, url, title) VALUES(69,'https://blog.starkandwayne.com/2014/11/19/running-logsearch-on-bosh-lite-in-10-minutes','Logsearch on Bosh-lite in 10 minutes');
INSERT INTO posts (orig_id, url, title) VALUES(78,'https://blog.starkandwayne.com/2014/12/30/live-github-pr-status-in-your-blogs-docs','How to embed live Github PR status in your blogs & docs');
INSERT INTO posts (orig_id, url, title) VALUES(51,'https://blog.starkandwayne.com/2014/08/01/aggregating-cloud-foundry-component-logs','Making Support happy: aggregating Cloud Foundry component logs');
INSERT INTO posts (orig_id, url, title) VALUES(71,'https://blog.starkandwayne.com/2014/12/04/how-to-install-go-on-digital-ocean','How To Install Go on Digital Ocean with a CentOS7 Droplet');
INSERT INTO posts (orig_id, url, title) VALUES(107,'https://blog.starkandwayne.com/2015/05/04/updates-to-terraform-aws-cf-install-and-terraform-openstack-cf-install','Updates to terraform-aws-cf-install and terraform-openstack-cf-install');
INSERT INTO posts (orig_id, url, title) VALUES(73,'https://blog.starkandwayne.com/2014/12/05/code-spelunking-to-build-a-cf-plugin','Code spelunking to build a CF Plugin');
INSERT INTO posts (orig_id, url, title) VALUES(72,'https://blog.starkandwayne.com/2014/12/05/introduction-cf-info-plugin','Introducing cf info plugin');
INSERT INTO posts (orig_id, url, title) VALUES(48,'https://blog.starkandwayne.com/2014/05/14/changing-root-password-on-mysql-5-6','Automating root password on MySQL 5.6');
INSERT INTO posts (orig_id, url, title) VALUES(110,'https://blog.starkandwayne.com/2015/05/06/configuring-openstack-for-cloud-foundry','Configuring OpenStack for Cloud Foundry');
INSERT INTO posts (orig_id, url, title) VALUES(75,'https://blog.starkandwayne.com/2014/12/16/running-cloud-foundry-locally-with-bosh-lite','Running Cloud Foundry Locally with BOSH Lite');
INSERT INTO posts (orig_id, url, title) VALUES(70,'https://blog.starkandwayne.com/2014/12/17/introduction-to-cloud-foundrys-health-monitor','Introduction to Cloud Foundry''s Health Monitor');
INSERT INTO posts (orig_id, url, title) VALUES(93,'https://blog.starkandwayne.com/2015/03/27/staticfile-buildpack-v0-5-is-now-more-trusty','Staticfile buildpack v0.5 is now more trusty');
INSERT INTO posts (orig_id, url, title) VALUES(88,'https://blog.starkandwayne.com/2015/03/20/admin-scripting-your-way-around-cloud-foundry','Admin scripting your way around Cloud Foundry');
INSERT INTO posts (orig_id, url, title) VALUES(81,'https://blog.starkandwayne.com/2015/01/22/billing-your-cloud-foundry-users','Billing your Cloud Foundry users');
INSERT INTO posts (orig_id, url, title) VALUES(95,'https://blog.starkandwayne.com/2015/03/31/simple-alerts-for-all-disks-in-cloud-foundrybosh','Simple alerts for all disks in Cloud Foundry/BOSH');
INSERT INTO posts (orig_id, url, title) VALUES(98,'https://blog.starkandwayne.com/2015/04/02/inspecting-bosh-manifests-in-bash','Inspecting BOSH manifests in Bash');
INSERT INTO posts (orig_id, url, title) VALUES(111,'https://blog.starkandwayne.com/2015/05/06/deploying-cloud-foundry-on-openstack-using-terraform','Deploying Cloud Foundry on OpenStack using Terraform');
INSERT INTO posts (orig_id, url, title) VALUES(99,'https://blog.starkandwayne.com/2015/04/13/keeping-an-eye-on-cloud-foundry-pt-2','Keeping an eye on Cloud Foundry Pt. 2');
INSERT INTO posts (orig_id, url, title) VALUES(100,'https://blog.starkandwayne.com/2015/04/06/deploy-cloud-foundry-on-aws-using-terraform','Easy Deployment of Cloud Foundry on AWS using Terraform');
INSERT INTO posts (orig_id, url, title) VALUES(74,'https://blog.starkandwayne.com/2014/12/24/traveling-bosh-cli-no-more-installation-pain','Traveling BOSH CLI - no more installation pain');
INSERT INTO posts (orig_id, url, title) VALUES(109,'https://blog.starkandwayne.com/2015/05/05/openstack-juno-static-ip-patch','OpenStack Juno Static IP Patch');
INSERT INTO posts (orig_id, url, title) VALUES(96,'https://blog.starkandwayne.com/2015/03/31/decomposing-bosh-manifests-with-spiff','Composing BOSH manifests with Spiff');